[unstable]
build-std-features=["compiler-builtins-mem"]
build-std=["core","compiler_builtins"]


[build]
target="x86_64-blog_os.json"


[dependencies.lazy_static]
version="1.0"
features=["spin_no_std"]